spring:
  application:
    name: auth-service
  profiles:
    active: dev

server:
  port: 8081

app:
  jwt:
    # Secreto Base64 (256 bits). En produccion usar env var: APP_JWT_SECRET
    secret: ${APP_JWT_SECRET:cmVzcG9uc3lzLXNlY3JldC1rZXktMjAyNC1taW5pbXVtLTI1Ni1iaXRz}
    expiration-ms: 86400000  # 24 horas

logging:
  level:
    com.responsys: DEBUG
